services:
  db:
    container_name: iris_systems_rec_task_development
    image: mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    # ports:
    #   - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql # volume mapping
  app: 
    container_name: iris_compose
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT # https://docs.docker.com/compose/support-and-feedback/faq/#why-do-my-services-take-10-seconds-to-recreate-or-stop
    ports: 
      - "8080:3000"
    volumes:
      - .:/app
    env_file: .env
    # environment:
    #   RAILS_ENV: development
    depends_on:
      - db
volumes:
  mysql_data: