services:
  db:
    container_name: iris_systems_rec_task_development
    image: mysql
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    # ports:
    #   - "3306:3306"
    expose:
      - "3306"
    volumes: # named persistence
      - mysql_data:/var/lib/mysql # volume mapping
  app: 
    # container_name: iris_compose
    # we will have to remove container name since replicas are ignored if container_name is present, check resources link 1.
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT # https://docs.docker.com/compose/support-and-feedback/faq/#why-do-my-services-take-10-seconds-to-recreate-or-stop
    # ports: 
    #   - "8080:3000"
    expose:
      - "3000"
    volumes:
      - .:/app
      - /app/tmp/pids
    env_file: .env
    # environment:
    #   RAILS_ENV: development
    deploy:
      # mode: replicated default is replicated apparently
      replicas: 3
    depends_on:
      - db

  reverse_proxy:
    container_name: iris_reverse_proxy
    image: nginx
    ports:
      - "80:80"
      - "443:443" # for https
    volumes: # bind persistence
      - ./custom-nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - app

volumes:
  mysql_data: