services:
  app: 
    container_name: iris_compose
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "80:3000"
    volumes:
      - .:/app
      # - gem_cache:/usr/local/bundle/gems
      # - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development